#cloud-config
hostname: gitruner
manage_etc_hosts: true
users:
  - name: wally
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
chpasswd:
  list: |
    wally:123
  expire: False
ssh_pwauth: True
timezone: America/Sao_Paulo
runcmd:
  - timedatectl set-ntp true
  - apt update && apt upgrade -y && apt install -y curl jq
  - su - wally -c "export RUNNER_CFG_PAT=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 && curl -s https://raw.githubusercontent.com/actions/runner/main/scripts/create-latest-svc.sh | bash -s wallacedefreitas/bashscripts"