#cloud-config
hostname: gitruner

users:
  - name: wally
    groups: sudo,docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
chpasswd:
  list: |
    wally:123
  expire: False
ssh_pwauth: True
timezone: America/Sao_Paulo

package_upgrade: true
package_update: true

packages:
  - curl
  - jq
  - docker.io
  - docker-buildx
  - sshpass

runcmd:
  - timedatectl set-ntp true