#cloud-config
hostname: gitruner
manage_etc_hosts: true
users:
  - name: wally
    groups: sudo,docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
chpasswd:
  list: |
    wally:123
  expire: False
ssh_pwauth: True
timezone: America/Sao_Paulo
runcmd:
  - timedatectl set-ntp true
  - apt update && apt upgrade -y && apt install -y curl jq docker.io